### ISSUE TITLE
toxbootGetMongoFields defaults to 1000 documents

### ISSUE THREAD

**Issue by jasbner** [ericwatt/toxboot#10]
When calling toxbootGetMongoFields the maximum number of documents that will be surfaced is 1000 most likely due to the batch function default in mongolite.  Ideally I'd like to be able to return all matching documents.

**Comment by ericwatt** [comment]
I agree that this needs to return all results. I'll take `num_results`, the number of documents that match the query calculated just before, and pass it as the size argument to `batch`.

Thanks for the heads up. I don't think I tried more than 1000 documents since switching to `mongolite` so I missed this issue.
